<?php

use Drupal\Core\Access\AccessResult;
use Drupal\node\Entity\Node;
use Drupal\group\Entity\Group;

/**
 * Implements hook_entity_view().
 */
function iq_events_entity_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode)
{
  if ($entity->getEntityTypeId() == 'node' && $entity->bundle() == 'iq_event') {
    foreach ($build['field_iq_event_instances']['#items'] as $key => $instance) {
      $instance = Node::load($instance->getValue()['target_id']);
      if (!empty($instance) && $instance->hasField('field_iq_capacity') && $instance->hasField('field_iq_number_registrations')) {

        if ($instance->field_iq_capacity->value == $instance->field_iq_number_registrations->value) {
          $build['field_iq_event_instances']['#items'][$key] = [
            '#type' => 'markup',
            '#markup' => '<p>The Registration is closed (The event is full).</p>'
          ];
          //unset($build['field_iq_event_instances']['#items'][$key]);
        }
      }
    }

  }
}

/**
 * Implements hook_entity_view_display_alter().
 */
function iq_events_entity_view_display_alter(\Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, array $context)
{
  $node = \Drupal::routeMatch()->getParameter('node');
  if (!empty($node)) {
  }
  foreach ($display->getComponents() as $name => $options) {

  }

}

/**
 * Implements hook_form_alter().
 */
function iq_events_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{
}

function iq_events_webform_submission_delete(\Drupal\webform\WebformSubmissionInterface $webform_submission) {
  $values = $webform_submission->getData();
  if (!empty($values['iq_event_instance'])) {
    // @TODO: See how many people are registered with the webform.
    $nr_persons = 1;
    $event_instance = Node::load($values['iq_event_instance']);
    if (!empty($values['iq_nr_persons'])) {
      $nr_persons += $values['iq_nr_persons'];
    }

    if (!empty($event_instance)) {
      $number_of_registrations = $event_instance->field_iq_number_registrations->value;
      $occupied_places = $number_of_registrations - $nr_persons;
      if ($occupied_places < 0) {
        $occupied_places = 0;
      }
      $event_instance->set('field_iq_number_registrations', $occupied_places);
      $event_instance->save();
    }
  }
}

/**
 * Implements hook_webform_element_alter().
 */
function iq_events_webform_element_alter(array &$element, \Drupal\Core\Form\FormStateInterface $form_state, array $context)
{
  $form = $context['form'];
  \Drupal::logger('iq_events')->notice(json_encode(array_keys($element)));
  $node = \Drupal::routeMatch()->getParameter('node');
  if (!empty($node) && $node->bundle() == 'iq_event') {
    if ($element['#webform_key'] == "iq_event_instance") {
      if (!empty($form['#attributes']['class'])) {
        foreach ($form['#attributes']['class'] as $class) {
          if (preg_match('/^.*node\-[0-9]+\-form$/', $class)) {
            $event_instance_id = explode('-', explode('-node-', $class)[1])[0];
            $event_instances = \Drupal::entityTypeManager()->getStorage('node')->loadByProperties([
              'type' => 'iq_event_instance',
              'nid' => $event_instance_id
            ]);
            $event_instance = reset($event_instances);
            if (!empty($event_instance)) {
              $element['#default_value'] = $event_instance;
            }
          }
        }
      }
    }
    else if ($element['#webform_key'] == "iq_event") {
        $element['#default_value'] = $node;
    }
  }
}


/**
 * Implements hook_ENTITY_TYPE_access().
 */
function iq_events_node_access(\Drupal\Core\Entity\EntityInterface $entity, $operation, \Drupal\Core\Session\AccountInterface $account)
{
  if ($entity->bundle() == 'iq_event') {
    $user = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
    $generalGroup = Group::load(\Drupal::config('iq_group.settings')->get('general_group_id'));

    if (!empty($generalGroup) && $generalGroup->getMember($account)) {
      return AccessResult::neutral();
    }
    else {
      return AccessResult::forbidden('Non-group members cannot access');
    }
  }
}
